kind: Deployment
apiVersion: apps.openshift.io/v1
metadata:
  name: hello-service
  labels:
    app: hello-service
    app.kubernetes.io/component: hello-service
    app.kubernetes.io/instance: hello-service
spec:
  replicas: 1
  selector:
    deploymentconfig: hello-service
  template:
    metadata:
      labels:
        deploymentconfig: hello-service
    spec:
      containers:
        - name: hello-service
          image: image-registry.openshift-image-registry.svc:5000/hello-spring-dev/hello-service
          ports:
            - containerPort: 8778
              protocol: TCP

